'use strict';
(function(){
  const API='https://fundfxt.onrender.com';
  const BQ='https://biquote.io/api/latest?';
  const SYMBOLS=['EURUSD','GBPUSD','USDJPY','USDCHF','AUDUSD','USDCAD','NZDUSD','EURGBP','EURJPY','EURAUD','EURCHF','EURNZD','GBPJPY','GBPCHF','GBPAUD','GBPNZD','AUDJPY','AUDNZD','AUDCAD','AUDCHF','CADJPY','CADCHF','CHFJPY','NZDJPY','NZDCHF','NZDCAD','XAUUSD','XAGUSD'];
  const $=id=>document.getElementById(id);
  const state={account:null,prices:{},symbols:[...SYMBOLS],selected:'EURUSD',tab:'OPEN'};
  const token=()=>localStorage.getItem('fundfxt_token')||'';
  const headers=()=>({Authorization:'Bearer '+token(),'Content-Type':'application/json'});
  const price=(v,s)=>{const n=Number(v);if(!Number.isFinite(n))return'—';return n.toFixed(/JPY$/i.test(s)?3:/XAU|XAG|BTC|ETH/i.test(s)?2:5)};
  const money=v=>'$'+(Number(v||0)/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
  async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...headers(),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||('HTTP '+r.status));return d}
  async function biquote(){const r=await fetch(BQ+SYMBOLS.map(s=>'symbols='+encodeURIComponent(s)).join('&'),{headers:{Accept:'application/json'}});if(!r.ok)throw Error('BiQuote HTTP '+r.status);const body=await r.json();return body?.data&&typeof body.data==='object'&&!Array.isArray(body.data)?body.data:body}
  function normalize(data){const out={};for(const [k,q] of Object.entries(data||{})){const bid=Number(q?.bid),ask=Number(q?.ask);if(Number.isFinite(bid)&&Number.isFinite(ask))out[k.toUpperCase()]={...q,bid,ask,mid:Number.isFinite(Number(q.mid))?Number(q.mid):(bid+ask)/2}}return out}
  function live(){const m=$('market');if(!m)return;const ok=Object.values(state.prices).some(q=>Number.isFinite(q?.bid)&&Number.isFinite(q?.ask));m.textContent=ok?'● LIVE':'● OFFLINE';m.style.color=ok?'#00d084':'#ff4444'}
  function renderQuotes(){const box=$('watchlist');if(!box)return;const term=($('search')?.value||'').trim().toLowerCase();const list=state.symbols.filter(s=>s.toLowerCase().includes(term));box.innerHTML=list.map(s=>{const p=state.prices[s]||{},mid=Number.isFinite(p.mid)?p.mid:(Number.isFinite(p.bid)&&Number.isFinite(p.ask)?(p.bid+p.ask)/2:NaN),sp=Number.isFinite(p.bid)&&Number.isFinite(p.ask)?Math.abs(p.ask-p.bid):NaN,ch=Number(p.changePercent);return '<button class="quote '+(s===state.selected?'selected':'')+'" data-runtime-symbol="'+s+'"><span class="quote-main"><b class="watch-symbol">'+s+'</b><span class="quote-detail quote-change">Δ '+(Number.isFinite(ch)?(ch>=0?'+':'')+ch.toFixed(2)+'%':'—')+'</span></span><span class="quote-spread">— '+price(sp,s)+' —</span><span class="quote-mid"><small>MID</small><b>'+price(mid,s)+'</b></span></button>'}).join('')||'<div class="empty"><strong>No symbols found</strong><span>Try another symbol.</span></div>';box.querySelectorAll('[data-runtime-symbol]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.runtimeSymbol;renderQuotes();renderSelected();renderOrder();show('center')});live()}
  function renderSelected(){const p=state.prices[state.selected]||{},mid=Number.isFinite(p.mid)?p.mid:(Number.isFinite(p.bid)&&Number.isFinite(p.ask)?(p.bid+p.ask)/2:NaN);if($('selectedSymbol'))$('selectedSymbol').textContent=state.selected;if($('selectedPrice'))$('selectedPrice').textContent='Last '+price(mid,state.selected)+' • Bid '+price(p.bid,state.selected)+' • Ask '+price(p.ask,state.selected)+' • Spread '+price(p.ask-p.bid,state.selected);if($('chartSource'))$('chartSource').textContent='TRADINGVIEW CHART · BIQUOTE EXECUTION FEED'}
  function renderOrder(){const p=state.prices[state.selected]||{};if($('buy')){$('buy').textContent='BUY '+price(p.ask,state.selected);$('buy').disabled=!Number.isFinite(p.ask)}if($('sell')){$('sell').textContent='SELL '+price(p.bid,state.selected);$('sell').disabled=!Number.isFinite(p.bid)}if($('quoteBox'))$('quoteBox').innerHTML='<span class="execution-bid">BID <b>'+price(p.bid,state.selected)+'</b></span><span class="execution-ask">ASK <b>'+price(p.ask,state.selected)+'</b></span><span class="execution-spread">S <b>'+price(p.ask-p.bid,state.selected)+'</b></span>'}
  function chart(){const host=$('tv');if(!host)return;const interval=document.querySelector('.tf.active')?.dataset.interval||'15';const key=state.selected+'|'+interval;if(host.dataset.runtimeKey===key&&host.querySelector('iframe'))return;host.dataset.runtimeKey=key;host.innerHTML='';const f=document.createElement('iframe');f.title='FundFXT TradingView '+state.selected;f.allowFullscreen=true;f.style.cssText='display:block;width:100%;height:100%;min-height:320px;border:0;background:#0b0f14';f.src='https://www.tradingview.com/widgetembed/?symbol='+encodeURIComponent('OANDA:'+state.selected)+'&interval='+encodeURIComponent(interval)+'&theme=dark&style=1&locale=en&toolbar_bg=%230b0f14&enable_publishing=false&hide_top_toolbar=false&hide_side_toolbar=false&save_image=false&autosize=true&support_host=https%3A%2F%2Fwww.tradingview.com';host.appendChild(f);$('chartFallback')?.classList.add('hidden')}
  function show(name){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('mobile-active'));$(name)?.classList.add('mobile-active');document.querySelectorAll('.mobile-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='center')chart();if(name==='right')loadTrades()}
  function renderTrades(rows){const box=$('tradeScroll');if(!box)return;const visible=rows.filter(t=>state.tab==='OPEN'?t.status==='OPEN':state.tab==='PENDING'?t.status==='PENDING':t.status==='CLOSED');box.innerHTML=visible.map(t=>'<article class="trade-card"><div class="trade-top"><div><b>'+t.symbol+'</b><small>'+String(t.trade_id||'Position')+'</small></div><span class="side '+(t.side==='SELL'?'sell':'')+'">'+t.side+' · '+t.volume+'</span></div><div class="trade-meta"><div><span>Entry</span><b>'+price(t.entry_price,t.symbol)+'</b></div><div><span>Current</span><b>'+price(t.current_price,t.symbol)+'</b></div><div><span>Status</span><b>'+t.status+'</b></div></div></article>').join('')||'<div class="empty"><strong>No '+state.tab.toLowerCase()+' trades</strong><span>Nothing is currently recorded for this account.</span></div>'}
  async function loadTrades(){if(!state.account)return;try{const d=await api('/api/trade/get?account_code='+encodeURIComponent(state.account.account_code));renderTrades(Array.isArray(d.trades)?d.trades:[])}catch(e){const box=$('tradeScroll');if(box)box.innerHTML='<div class="empty"><strong>Trade sync failed</strong><span>'+e.message+'</span></div>'}}
  function accountMenu(){const top=document.querySelector('.top-right');if(!top||$('fxRuntimeAccountBtn'))return;const b=document.createElement('button');b.id='fxRuntimeAccountBtn';b.className='icon-btn';b.type='button';b.title='Account';b.innerHTML='<i data-lucide="user-round"></i>';top.appendChild(b);const m=document.createElement('div');m.id='fxRuntimeMenu';m.className='fx-account-menu';m.hidden=true;m.innerHTML='<div class="fx-menu-head"><div><strong>Trading Account</strong><small id="rtStatus">Loading…</small></div><button class="fx-menu-close" id="rtClose">×</button></div><div class="fx-menu-section"><span>Account ID</span><b id="rtCode">—</b></div><div class="fx-menu-section"><strong>Account Rules & Compliance</strong><div class="fx-rule"><span>Daily Drawdown</span><b id="rtDD">—</b></div><div class="fx-rule"><span>Max Drawdown</span><b id="rtMaxDD">—</b></div><div class="fx-rule"><span>Max Trades</span><b id="rtMaxTrades">3</b></div></div><div class="fx-menu-section"><strong>Profile</strong><div class="fx-profile"><span>Status</span><b id="rtProfileStatus">—</b></div><div class="fx-profile"><span>Balance</span><b id="rtBalance">—</b></div><div class="fx-profile"><span>Equity</span><b id="rtEquity">—</b></div></div><button class="fx-menu-action" id="rtSettings"><i data-lucide="settings"></i> Settings</button><button class="fx-menu-action danger" id="rtLogout"><i data-lucide="log-out"></i> Logout</button>';document.body.appendChild(m);b.onclick=()=>{m.hidden=!m.hidden;if(!m.hidden)refreshMenu()};$('rtClose').onclick=()=>m.hidden=true;$('rtLogout').onclick=()=>{localStorage.removeItem('fundfxt_token');localStorage.removeItem('fundfxt_selected_account');location.href='/login.html'};$('rtSettings').onclick=()=>location.href='/settings.html';document.addEventListener('click',e=>{if(!m.contains(e.target)&&e.target!==b&&!b.contains(e.target))m.hidden=true});window.lucide?.createIcons?.();refreshMenu();setInterval(refreshMenu,5000)}
  async function refreshMenu(){const code=state.account?.account_code||localStorage.getItem('fundfxt_selected_account');if(!code)return;try{const d=await api('/api/accounts');const list=Array.isArray(d)?d:(d.accounts||[]),a=list.find(x=>String(x.account_code)===String(code))||list[0];if(!a)return;state.account=a;$('rtCode').textContent=a.account_code||code;$('rtStatus').textContent=(a.status||'ACTIVE')+' · Live';$('rtProfileStatus').textContent=a.status||'ACTIVE';$('rtBalance').textContent=money(a.balance_cents);$('rtEquity').textContent=money(a.equity_cents);$('rtDD').textContent=a.daily_drawdown_percent!=null?Number(a.daily_drawdown_percent).toFixed(2)+'%':'—';$('rtMaxDD').textContent=a.max_drawdown_percent!=null?Number(a.max_drawdown_percent).toFixed(2)+'%':'—';$('rtMaxTrades').textContent=a.max_trades??3}catch(e){}}
  async function sync(){try{let d;try{d=await api('/api/prices')}catch{d={prices:await biquote()}};let p=normalize(d.prices||d);if(Object.keys(p).length<SYMBOLS.length){try{p={...p,...normalize(await biquote())}}catch{}}state.prices=p;state.symbols=[...new Set([...SYMBOLS,...Object.keys(p)])];renderQuotes();renderSelected();renderOrder();if(state.account)loadTrades();live()}catch(e){const m=$('market');if(m){m.textContent='● OFFLINE';m.style.color='#ff4444'}}}
  async function init(){if(!token()){location.href='/login.html';return}try{const d=await api('/api/accounts');const list=Array.isArray(d)?d:(d.accounts||[]);const wanted=new URLSearchParams(location.search).get('account_code')||new URLSearchParams(location.search).get('account')||localStorage.getItem('fundfxt_selected_account');state.account=(wanted&&list.find(x=>String(x.account_code)===String(wanted)))||list[0]||null;if(state.account)localStorage.setItem('fundfxt_selected_account',state.account.account_code)}catch{}await sync();if(state.account){$('rightAccount').textContent=state.account.account_code;try{const d=await api('/api/accounts/'+state.account.id+'/summary');state.account={...state.account,...(d.account||d)};if($('balance'))$('balance').textContent=money(state.account.balance_cents);if($('equity'))$('equity').textContent=money(state.account.equity_cents)}catch{}}renderTrades([]);chart();accountMenu();setInterval(sync,1000)}
  document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.mobile-nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('.right-tab').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;document.querySelectorAll('.right-tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===state.tab));loadTrades()});$('search')?.addEventListener('input',renderQuotes);document.querySelectorAll('.tf').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tf').forEach(x=>x.classList.remove('active'));b.classList.add('active');chart()});init()});
})();
