services:
  - type: web
    name: fundfxt-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/boot.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
