from pathlib import Path

p = Path('backend/server.js')
s = p.read_text(encoding='utf-8')
old = '''// ========== WEBSOCKET SERVER ==========\nconst PORT = process.env.PORT || 3000;\nlet server;\n(async () => {\n  try {\n    await ensureAffiliateSchema();\n  } catch (migrationError) {\n    console.error('Affiliate schema repair failed:', migrationError.message);\n  }\n  server = app.listen(PORT, () =>\n    console.log(`🚀 Server running on port ${PORT}`),\n  );\n})();\nconst wss = new WebSocket.Server({ server, path: "/ws" });\n\nsetInterval(() => {\n  if (global.prices && Object.keys(global.prices).length > 0) {\n    const msg = JSON.stringify({ type: "price", data: global.prices });\n    wss.clients.forEach((client) => {\n      if (client.readyState === WebSocket.OPEN) client.send(msg);\n    });\n  }\n}, 1000);\n\nwss.on("connection", (client) => {\n  console.log("Frontend WebSocket connected");\n  client.send(JSON.stringify({ type: "price", data: global.prices || {} }));\n});'''
new = '''// ========== WEBSOCKET SERVER ==========\nconst PORT = process.env.PORT || 3000;\nlet server;\nlet wss;\n\n(async () => {\n  try {\n    await ensureAffiliateSchema();\n  } catch (migrationError) {\n    console.error('Affiliate schema repair failed:', migrationError.message);\n  }\n\n  server = app.listen(PORT, () =>\n    console.log(`🚀 Server running on port ${PORT}`),\n  );\n\n  // IMPORTANT: create WebSocketServer only after the HTTP server exists.\n  wss = new WebSocket.Server({ server, path: "/ws" });\n\n  wss.on("connection", (client) => {\n    console.log("Frontend WebSocket connected");\n    client.send(JSON.stringify({ type: "price", data: global.prices || {} }));\n  });\n})();\n\nsetInterval(() => {\n  if (wss && global.prices && Object.keys(global.prices).length > 0) {\n    const msg = JSON.stringify({ type: "price", data: global.prices });\n    wss.clients.forEach((client) => {\n      if (client.readyState === WebSocket.OPEN) client.send(msg);\n    });\n  }\n}, 1000);'''
if old not in s:
    raise SystemExit('Expected WebSocket startup block not found; refusing unsafe edit')
p.write_text(s.replace(old, new, 1), encoding='utf-8')
print('WebSocket startup block fixed')
