/* FundFXT Dashboard recovery layer — deterministic, no motion effects. */
(function(){
  'use strict';
  const API='https://fundfxt.onrender.com';
  const token=()=>localStorage.getItem('fundfxt_token')||'';
  const $=id=>document.getElementById(id);
  const money=c=>'$'+(Number(c||0)/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
  const esc=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  async function api(path){const r=await fetch(API+path,{headers:{Authorization:'Bearer '+token()}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||('Request failed ('+r.status+')'));return d}
  function installStyle(){if(document.getElementById('fundfxt-dashboard-recovery-style'))return;const s=document.createElement('style');s.id='fundfxt-dashboard-recovery-style';s.textContent='.dashboard-recovery-actions{display:flex;flex-wrap:wrap;gap:10px;margin:18px 0 28px}.dashboard-recovery-actions a{display:inline-flex;align-items:center;gap:8px;padding:11px 16px;border-radius:9px;text-decoration:none;font-weight:700;font-size:13px;border:1px solid var(--border);background:var(--bg-card);color:var(--text)}.dashboard-recovery-actions a.primary{background:var(--green);border-color:var(--green);color:#fff}.dashboard-recovery-error{padding:18px;border:1px solid rgba(255,68,68,.3);background:rgba(255,68,68,.06);border-radius:12px;color:#ff9a9a;grid-column:1/-1}.account-loading-card{padding:24px;text-align:center;color:var(--text-muted);border:1px solid var(--border);border-radius:12px}.dash-spinner{display:none}';document.head.appendChild(s)}
  function removeDuplicateNotification(){const bells=[...document.querySelectorAll('.bell-icon')];if(bells.length>1)bells.slice(1).forEach(b=>b.closest('.notification-container')?.remove()||b.remove())}
  function addQuickActions(){const home=$('view-home');if(!home||home.querySelector('.dashboard-recovery-actions'))return;const profile=home.querySelector('.profile-card'),actions=document.createElement('div');actions.className='dashboard-recovery-actions';actions.innerHTML='<a class="primary" href="/trading-terminal.html"><i class="fa-solid fa-chart-line"></i> Open Trading Terminal</a><a href="/account-dashboard.html"><i class="fa-solid fa-gauge-high"></i> Account Dashboard</a>';(profile||home.firstElementChild)?.insertAdjacentElement('afterend',actions)}
  function renderProfile(d){const name=d?.legal_name||'Trader';$('header-user-name')?.replaceChildren(document.createTextNode(name));$('profile-name')?.replaceChildren(document.createTextNode(name));if($('profile-email'))$('profile-email').textContent=d?.email||'—';if($('profile-phone'))$('profile-phone').textContent=d?.phone||'—';if($('profile-date'))$('profile-date').textContent=d?.member_since?new Date(d.member_since).toLocaleDateString():'—';if($('aff-code'))$('aff-code').textContent=d?.affiliate_code||'AFF-PENDING')}
  function accountCard(a){const p=a.account_profile||{},r=p.rules||{},initial=Number(a.initial_balance_cents||0),balance=Number(a.balance_cents||0),equity=Number(a.equity_cents??balance),profit=balance-initial,target=r.profitTargetCents==null?null:Number(r.profitTargetCents),progress=r.targetProgressPercent==null?0:Number(r.targetProgressPercent),status=String(a.status||'ACTIVE').toUpperCase(),code=a.account_code||'N/A';return `<div class="account-card" data-account-code="${esc(code)}"><span class="acc-status ${esc(status)}">${esc(status)}</span><h2>${esc(code)}</h2><div class="sub">${esc(p.accountType||p.model||a.challenge_model||'Trading Account')}</div><div class="account-info-grid"><p>Balance<strong>${money(balance)}</strong></p><p>Equity<strong>${money(equity)}</strong></p><p>Type<strong>${esc(p.accountType||'Trading Account')}</strong></p><p>Phase<strong>${esc(p.phase||'—')}</strong></p><p>Funding<strong>${esc(p.fundingModel||'—')}</strong></p><p>Profit<strong style="color:${profit>=0?'var(--green)':'var(--red)'}">${profit>=0?'+':''}${money(profit)}</strong></p></div><div style="margin:12px 0;font-size:11px;color:var(--text-muted)"><div style="display:flex;justify-content:space-between"><span>Profit target progress</span><b>${target===null?'Not configured':progress.toFixed(1)+'%'}</b></div><div style="height:7px;background:#2a2a2a;border-radius:10px;overflow:hidden;margin-top:6px"><i style="display:block;width:${Math.max(0,Math.min(100,progress))}%;height:100%;background:var(--green);border-radius:10px"></i></div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:7px;font-size:10px;color:var(--text-muted);margin-bottom:12px"><span>Daily DD left: <b>${r.dailyDrawdownRemainingCents==null?'—':money(r.dailyDrawdownRemainingCents)}</b></span><span>Max DD left: <b>${r.maxDrawdownRemainingCents==null?'—':money(r.maxDrawdownRemainingCents)}</b></span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><button class="view-btn account-dashboard-link" data-account="${esc(code)}" type="button">Open Dashboard</button><button class="view-btn terminal-link" data-account="${esc(code)}" type="button">Open Terminal</button></div></div>`}
  async function loadProfile(){try{renderProfile(await api('/api/user/profile'))}catch(e){console.error('FundFXT profile:',e)}}
  async function loadAccounts(){const c=$('accounts-container');if(!c)return;c.innerHTML='<div class="account-loading-card">Loading your trading accounts…</div>';try{const d=await api('/api/accounts'),accounts=Array.isArray(d.accounts)?d.accounts:[],active=accounts.filter(a=>String(a.status).toUpperCase()==='ACTIVE').length,passed=accounts.filter(a=>String(a.status).toUpperCase()==='PASSED').length,failed=accounts.filter(a=>['BREACHED','EXPIRED','CLOSED','FAILED'].includes(String(a.status).toUpperCase())).length,profit=accounts.reduce((s,a)=>s+Number(a.balance_cents||0)-Number(a.initial_balance_cents||0),0);if($('total-accounts'))$('total-accounts').textContent=accounts.length;if($('active-accounts'))$('active-accounts').textContent=active;if($('passed-accounts'))$('passed-accounts').textContent=passed;if($('failed-accounts'))$('failed-accounts').textContent=failed;if($('total-profit'))$('total-profit').textContent=(profit>=0?'+':'-')+money(Math.abs(profit));const empty=$('empty-state');if(!accounts.length){c.innerHTML='';if(empty)empty.style.display='block';return}if(empty)empty.style.display='none';c.innerHTML=accounts.map(accountCard).join('');c.querySelectorAll('.account-dashboard-link').forEach(b=>b.onclick=()=>location.href='/account-dashboard.html?account_code='+encodeURIComponent(b.dataset.account));c.querySelectorAll('.terminal-link').forEach(b=>b.onclick=()=>location.href='/trading-terminal.html?account_code='+encodeURIComponent(b.dataset.account))}catch(e){console.error('FundFXT accounts:',e);c.innerHTML='<div class="dashboard-recovery-error"><b>Trading accounts could not be loaded.</b><br>'+esc(e.message)+'</div>'}}
  async function recoverHome(){installStyle();removeDuplicateNotification();addQuickActions();await Promise.allSettled([loadProfile(),loadAccounts()])}
  const boot=setInterval(()=>{if(document.readyState!=='loading'&&document.getElementById('view-home')){clearInterval(boot);recoverHome()}},50);
})();
