const API_BASE_URL = "https://fundfxt.onrender.com";
const token = localStorage.getItem("fundfxt_admin_token");
if (!token) location.href = "login.html";
let users = [], orders = [], selectedOrder = null, currentSection = "dashboard";
const $ = (id) => document.getElementById(id);
const auth = () => ({ Authorization: "Bearer " + token, "Content-Type": "application/json" });
const esc = (v) => String(v ?? "").replace(/[&<>\'\"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '\"': "&quot;" })[c]);
const money = (c, cur = "USD") => `${String(cur).toUpperCase() === "USD" ? "$" : cur + " "}${(Number(c || 0) / 100).toFixed(2)}`;
const field = (o, ...names) => { for (const n of names) if (o && o[n] !== undefined && o[n] !== null && o[n] !== "") return o[n]; return ""; };
const orderRequestId = (o) => field(o, "request_id", "order_ref", "request_ref", "id");
const orderLink = (o) => field(o, "razorpay_link");
function toast(msg, type = "ok") { const t = $("toast"); if (!t) return alert(msg); t.textContent = msg; t.className = "toast show " + (type === "err" ? "err" : "ok"); clearTimeout(window.__toast); window.__toast = setTimeout(() => (t.className = "toast"), 3000); }
async function get(path) { const r = await fetch(API_BASE_URL + path, { headers: auth() }); let d = {}; try { d = await r.json(); } catch {} if (!r.ok) throw Error(d.error || d.message || `Request failed (${r.status})`); return d; }
async function post(path, body) { const r = await fetch(API_BASE_URL + path, { method: "POST", headers: auth(), body: JSON.stringify(body) }); let d = {}; try { d = await r.json(); } catch {} if (!r.ok) throw Error(d.error || d.message || `Request failed (${r.status})`); return d; }
function logout() { localStorage.removeItem("fundfxt_admin_token"); location.href = "login.html"; }
function toggleSidebar() { $("sidebar").classList.toggle("open"); }
function closeSidebarMobile() { $("sidebar").classList.remove("open"); }
function showSection(name) { currentSection = name; document.querySelectorAll(".view").forEach((x) => x.classList.remove("active")); const target = $("section-" + name); if (target) target.classList.add("active"); document.querySelectorAll(".nav button").forEach((x) => x.classList.toggle("active", x.dataset.section === name)); closeSidebarMobile(); const loaders = { dashboard: fetchDashboard, users: fetchUsers, orders: fetchOrders, withdrawals: fetchWithdrawals, affiliates: fetchAffiliates, certificates: fetchCertificates, support: fetchSupportTickets, settings: loadSettings }; if (loaders[name]) loaders[name](); }
function refreshCurrent() { showSection(currentSection); }
function setState(kind, loading = false, error = "") { const ids = { users: ["usersLoading", "usersEmpty", "usersError"], orders: ["ordersLoading", "ordersEmpty", "ordersError"], withdrawals: ["withdrawalsLoading", "withdrawalsEmpty", "withdrawalsError"], affiliates: ["affiliatesLoading", "affiliatesEmpty", "affiliatesError"], certificates: ["certificatesLoading", "certificatesEmpty", "certificatesError"], support: ["supportLoading", "supportEmpty", "supportError"] }[kind]; if (!ids) return; const [l,e,er]=ids; $(l).style.display=loading?"block":"none"; $(e).style.display="none"; $(er).innerHTML=error?`<div class="error-box">${esc(error)}</div>`:""; }
async function fetchDashboard(){try{const d=await get("/api/admin/dashboard-stats"),s=d.stats||{}; $("statPayments").textContent=s.payment_requests_today??0; $("statWithdrawals").textContent=s.withdrawal_requests_today??0; $("statPassed").textContent=s.passed_accounts_today??0; $("statFailed").textContent=s.failed_accounts_today??0; $("statRevenue").textContent=money(s.successful_revenue_cents);}catch(e){toast(e.message,"err");}}
async function fetchUsers(){setState("users",true);try{const d=await get("/api/admin/users");users=d.users||[];renderUsers();}catch(e){setState("users",false,e.message);}}
function renderUsers(){const q=($("userSearch").value||"").toLowerCase(),f=$("userFilter").value;const rows=users.filter(u=>(!f||String(u.kyc_status||"")===f)&&[u.id,u.legal_name,u.email,u.phone,u.trader_id,u.address,u.affiliate_code].some(v=>String(v??"").toLowerCase().includes(q)));$("usersBody").innerHTML=rows.map(u=>`<tr><td>${esc(u.id)}</td><td>${esc(u.trader_id)}</td><td><b>${esc(u.legal_name)}</b></td><td>${esc(u.email)}</td><td>${esc(u.phone)}</td><td>${esc(u.address||"—")}</td><td><span class="badge ${String(u.kyc_status)==="APPROVED"?"green":"yellow"}">${esc(u.kyc_status||"—")}</span></td><td>${esc(u.affiliate_code||"—")}</td><td>${u.created_at?new Date(u.created_at).toLocaleString():"—"}</td></tr>`).join("");$("usersLoading").style.display="none";$("usersEmpty").style.display=rows.length?"none":"block";}
async function fetchOrders(){setState("orders",true);try{const q=($("paymentSearch").value||"").trim(),s=$("orderStatusFilter").value;let qs=[];if(q)qs.push("request_id="+encodeURIComponent(q));if(s)qs.push("status="+encodeURIComponent(s));let d;try{d=await get("/api/admin/payment-orders"+(qs.length?"?"+qs.join("&"):""));}catch(first){if(q){let legacy=[];if(s)legacy.push("status="+encodeURIComponent(s));legacy.push("request_ref="+encodeURIComponent(q));d=await get("/api/admin/payment-orders?"+legacy.join("&"));}else throw first;}orders=d.orders||[];renderOrders();}catch(e){setState("orders",false,e.message);}}
function clearPaymentSearch(){$("paymentSearch").value="";$ ("orderStatusFilter").value="";fetchOrders();}
function statusClass(s){return s==="PAYMENT_APPROVED"||s==="ACCOUNT_CREATED"?"green":s==="REJECTED"||s==="CANCELLED"?"red":s==="PAYMENT_DONE"?"blue":"yellow";}
function renderOrders(){const rows=orders||[];$("ordersBody").innerHTML=rows.map(o=>{const rid=orderRequestId(o),link=orderLink(o);let action="";if(o.status==="REQUESTED")action=`<button class="btn" onclick='openLink(${JSON.stringify(o)})'>Proceed</button>`;else if(["LINK_SENT","PAYMENT_PENDING","PAYMENT_DONE"].includes(o.status))action=`<button class="btn secondary" onclick='openStatus(${JSON.stringify(o)})'>Verify / Update</button>`;else if(o.status==="PAYMENT_APPROVED")action=`<button class="btn" onclick='createAccount(${Number(o.id)})'>Create Account</button>`;else if(o.status==="ACCOUNT_CREATED")action=`<span class="badge green">${esc(field(o,"account_code")||"ACCOUNT CREATED")}</span>`;else action=`<button class="btn secondary" onclick='openStatus(${JSON.stringify(o)})'>Update</button>`;const linkHtml=link?`<a href="${esc(link)}" target="_blank" rel="noopener noreferrer" style="word-break:break-all">Open Link</a>`:"—";return `<tr><td><b>${esc(rid)}</b></td><td><b>${esc(field(o,"legal_name","name"))}</b><br><small>${esc(field(o,"user_email","email"))}</small></td><td>${esc(field(o,"model","model_key"))}</td><td>${esc(o.affiliate_code||"—")}<br><small>${esc(o.affiliate_name||"—")}</small></td><td>${money(o.original_amount_cents,o.currency)}</td><td>${money(o.discount_amount_cents,o.currency)}</td><td><b>${money(o.final_amount_cents,o.currency)}</b></td><td>${linkHtml}</td><td><span class="badge ${statusClass(o.status)}">${esc(o.status||"—")}</span></td><td>${action}</td></tr>`;}).join("");$("ordersLoading").style.display="none";$("ordersEmpty").style.display=rows.length?"none":"block";}
function openLink(o){selectedOrder=o;$("linkOrderInfo").innerHTML=`<b>Request ID:</b> ${esc(orderRequestId(o))}<br><b>Customer:</b> ${esc(field(o,"legal_name","name"))} (${esc(field(o,"user_email","email"))})<br><b>Challenge:</b> ${esc(field(o,"model","model_key"))}<br><b>Original:</b> ${money(o.original_amount_cents,o.currency)}<br><b>Discount:</b> ${money(o.discount_amount_cents,o.currency)}<br><b>Payable:</b> ${money(o.final_amount_cents,o.currency)}<br><b>Affiliate:</b> ${esc(o.affiliate_code||"—")} / ${esc(o.affiliate_name||"—")}`;$("paymentLinkInput").value=orderLink(o)||"";$("linkModal").classList.add("open");setTimeout(()=>$("paymentLinkInput").focus(),50);}
function closeLinkModal(){$("linkModal").classList.remove("open");selectedOrder=null;}
async function submitPaymentLink(){if(!selectedOrder)return;const link=$("paymentLinkInput").value.trim();if(!/^https:\/\//i.test(link))return toast("Enter a valid HTTPS Razorpay payment link.","err");try{const d=await post("/api/admin/payment-requests/"+selectedOrder.id+"/mark-link-sent",{razorpay_link:link});toast("Payment link saved and support email processed.");closeLinkModal();await fetchOrders();await fetchDashboard();if(d&&d.emailed_to)toast("Email sent to "+d.emailed_to);}catch(e){toast(e.message,"err");}}
function openStatus(o){selectedOrder=o;$("statusOrderInfo").innerHTML=`<b>Request ID:</b> ${esc(orderRequestId(o))}<br><b>Customer:</b> ${esc(field(o,"legal_name","name"))} (${esc(field(o,"user_email","email"))})<br><b>Challenge:</b> ${esc(field(o,"model","model_key"))}<br><b>Razorpay Link:</b> ${orderLink(o)?esc(orderLink(o)):"Not added"}<br><b>Payable:</b> ${money(o.final_amount_cents,o.currency)}<br><b>Current Status:</b> ${esc(o.status||"—")}`;$("statusModal").classList.add("open");}
function closeStatusModal(){$("statusModal").classList.remove("open");selectedOrder=null;}
async function setOrderStatus(s){if(!selectedOrder)return;if(!confirm("Set "+orderRequestId(selectedOrder)+" to "+s+"?"))return;try{await post("/api/admin/payment-orders/"+selectedOrder.id+"/status",{status:s});closeStatusModal();toast("Payment status updated.");await fetchOrders();await fetchDashboard();}catch(e){toast(e.message,"err");}}
async function createAccount(id){if(!confirm("Payment is APPROVED. Create the challenge account now?"))return;try{const d=await post("/api/admin/payment-orders/"+id+"/create-account",{});toast("Account created: "+(d.account_code||"success"));await fetchOrders();await fetchDashboard();}catch(e){toast(e.message,"err");}}
async function fetchWithdrawals(){setState("withdrawals",true);try{const d=await get("/api/admin/withdrawals"),rows=d.withdrawals||[];$("withdrawalsBody").innerHTML=rows.map(x=>`<tr><td><b>${esc(field(x,"request_id","request_ref","id"))}</b></td><td><b>${esc(field(x,"legal_name","name"))}</b><br><small>${esc(field(x,"user_email","email"))}</small></td><td>${esc(x.account_code||"—")}</td><td>${money(x.amount_cents,x.currency)}</td><td>${esc(x.method||"—")}</td><td><span class="badge ${String(x.status).toUpperCase().includes("PAID")?"green":"yellow"}">${esc(x.status||"—")}</span></td></tr>`).join("");$("withdrawalsLoading").style.display="none";$("withdrawalsEmpty").style.display=rows.length?"none":"block";}catch(e){setState("withdrawals",false,e.message);}}
async function fetchAffiliates(){setState("affiliates",true);try{const d=await get("/api/admin/affiliates"),rows=d.affiliates||[];$("affiliatesBody").innerHTML=rows.map(x=>`<tr><td><b>${esc(x.legal_name)}</b></td><td>${esc(x.email)}</td><td><b>${esc(x.affiliate_code||"—")}</b></td><td>${x.total_sales||0}</td><td>${money(x.total_earnings_cents)}</td><td>${money(x.pending_earnings_cents)}</td><td>${x.affiliate_code?`<button class="copy-btn" onclick="copyText(${JSON.stringify(String(x.affiliate_code))})">Copy Code</button>`:"—"}</td></tr>`).join("");$("affiliatesLoading").style.display="none";$("affiliatesEmpty").style.display=rows.length?"none":"block";}catch(e){setState("affiliates",false,e.message);}}
async function copyText(v){try{await navigator.clipboard.writeText(v);toast("Affiliate code copied.");}catch{toast(v);}}
async function fetchCertificates(){setState("certificates",true);try{const d=await get("/api/admin/certificates"),rows=d.certificates||[];$("certificatesBody").innerHTML=rows.map(x=>`<tr><td><b>${esc(x.legal_name)}</b></td><td>${esc(x.account_code||"—")}</td><td>${esc(x.achievement||"—")}</td><td>${esc(x.issued_on||x.created_at||"—")}</td></tr>`).join("");$("certificatesLoading").style.display="none";$("certificatesEmpty").style.display=rows.length?"none":"block";}catch(e){setState("certificates",false,e.message);}}
async function fetchSupportTickets(){setState("support",true);try{const d=await get("/api/admin/support/tickets"),rows=d.tickets||[];$("supportBody").innerHTML=rows.map(x=>`<tr><td><b>${esc(x.ticket_ref||x.id)}</b></td><td>${esc(x.legal_name||x.email||"—")}</td><td>${esc(x.title||x.subject||"—")}</td><td style="max-width:420px">${esc(x.message||"—")}</td><td>${esc(x.created_at||"—")}</td></tr>`).join("");$("supportLoading").style.display="none";$("supportEmpty").style.display=rows.length?"none":"block";}catch(e){setState("support",false,e.message);}}
async function loadSettings(){try{const d=await get("/api/settings"),s=d.settings||d,mode=String(s.payment_mode?.mode||s.payment_mode||"MANUAL").toUpperCase();document.querySelectorAll("[name=paymentMode]").forEach(x=>x.checked=x.value===mode);$("maintenanceMode").checked=Boolean(s.maintenance_mode?.enabled||s.maintenance_mode);}catch(e){$("settingsError").innerHTML=`<div class="error-box">${esc(e.message)}</div>`;}}
async function saveSettings(){try{const mode=document.querySelector("[name=paymentMode]:checked")?.value||"MANUAL";await post("/api/admin/settings",{settings:{payment_mode:{mode},maintenance_mode:{enabled:$("maintenanceMode").checked}}});$("settingsMsg").textContent="Saved successfully";toast("Settings saved.");setTimeout(()=>($("settingsMsg").textContent=""),2200);}catch(e){toast(e.message,"err");}}
document.addEventListener("keydown",(e)=>{if(e.key==="Escape"){closeLinkModal();closeStatusModal();closeSidebarMobile();}});
showSection("dashboard");

// Database Control is kept as a separate module so the main admin controller remains focused on business operations.
const databaseControlScript = document.createElement("script");
databaseControlScript.src = "database-control.js?v=20260911";
databaseControlScript.defer = true;
document.head.appendChild(databaseControlScript);
